# https://github.com/zivong/jekyll-theme-hydure

remote_theme: zivong/jekyll-theme-hydure


plugins:
  - jekyll-remote-theme

title: 'storm in a teacup'
tagline: 'thoughts, one sip at a time'

author.name : 'stormtoast'
author.url : 'http://stormtoast.gihub.io'
tags_path : '/tags' 
categories_path: '/categories' 
cover : '/assets/img/cover.jpg'