
# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup

title: StormInAeTacup
tagline: 'thoughts, one sip at a time'
description: 'a description here'

url: http://stormtoast.github.io
baseurl: /

author:
    name: 'stormtoast'

paginate:   5

# Custom vars
version:          0.0.1

github:
  repo:  https://github.com/stormtoast
